# Generated by Django 5.1.5 on 2025-02-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_inboxmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-latest_message']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='last_message_created',
            new_name='latest_message',
        ),
    ]
