# Generated by Django 5.1.5 on 2025-02-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_created']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='latest_message',
            new_name='last_message_created',
        ),
    ]
