# Generated by Django 5.1.4 on 2025-01-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
