# Generated by Django 5.1.4 on 2025-01-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0002_post_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.CharField(max_length=300),
        ),
    ]
