# Generated by Django 5.1.5 on 2025-02-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_fondo',
            field=models.FileField(upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.FileField(upload_to='posts'),
        ),
    ]
