# Generated by Django 5.1.5 on 2025-02-08 04:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0003_alter_post_imagen_fondo_alter_post_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_fondo',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
