# Generated by Django 5.1.4 on 2025-01-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0003_alter_post_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_fondo',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
