# Generated by Django 5.1.4 on 2025-01-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0004_remove_post_imagen_post_imagen_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_fondo',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
