# Generated by Django 5.1.5 on 2025-02-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0005_remove_post_image_alter_post_imagen_fondo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
