# Generated by Django 5.1.5 on 2025-02-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justicia_app', '0007_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created'], 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
